on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
  - name: Checkout
    uses: actions/checkout@v2
  - run: git fetch --unshallow --tags
  - name: auto release
    uses: terradatum/auto-action@master
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      email: kbaz@gmail.com
      name: Kathy Baz
      command: release
      plugins: |
        npm
        git-tag
        releases
   
